nameOverride: null
fullnameOverride: null
homeassistant:
  hostname: homeassistant.home
  image: ghcr.io/home-assistant/home-assistant:stable
  containerPort: 8123
  hostNetwork: false
  config:
    TZ: "Europe/Berlin"
  zigbeeDevice: null
  storage: 1Gi

  initConfig: |
    default_config:
    frontend:
      themes: !include_dir_merge_named themes

    tts:
      - platform: google_translate

    automation: !include_dir_list automations
    script: !include_dir_list scripts
    scene: !include_dir_list scenes
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/24
