nameOverride: null
fullnameOverride: null

homeassistant:
  # -- The reference to a secret containing admin credentials
  # Should have two keys USERNAME and PASSWORD
  adminSecret: null

  # -- The hostname for Home Assistant
  hostname: homeassistant.home


  image:
    # -- The Home Assistant image to use
    path: ghcr.io/home-assistant/home-assistant
    # -- The Home Assistang image tag
    # @default `{{ .Chart.AppVersion }}`
    tag: latest


  # -- The reference to the Zigbee device to use with Home Assistant
  zigbeeDevice: null

  # -- The storage size for Home Assistant
  storage: 1Gi

  reloader:
    # -- The reloader image to use for applying changes
    image: kiwigrid/k8s-sidecar:latest

    # -- The webhook ID for the reloader
    # Generate a random value to be used for reloading webhooks.
    webhook_id:

    automations:
      # -- Whether to enable automations
      enabled: true

      # -- The label for automations
      label: homeassistant.automations

    scripts:
      # -- Whether to enable scripts
      enabled: true

      # -- The label for scripts
      label: homeassistant.scripts

    scenes:
      # -- Whether to enable scenes
      enabled: true

      # -- The label for scenes
      label: homeassistant.scenes

    themes:
      # -- Whether to enable themes
      enabled: true

      # -- The label for themes
      label: homeassistant.themes

  # -- The initial configuration for Home Assistant
  config: |
    default_config:

    homeassistant:
      name: Home
      latitude: 31.7780191
      longitude: 35.2354079
      elevation: 747
      unit_system: metric
      currency: PAL
      country: PS
      time_zone: "Asia/Jerusalem"
      language: "en"

    frontend:
      themes: !include_dir_merge_named themes

    tts:
      - platform: google_translate

    automation: !include_dir_list automations
    automation ui: !include automations.yaml
    script: !include_dir_list scripts
    script ui: !include scripts.yaml
    scene: !include_dir_list scenes
    scene ui: !include scenes.yaml

    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/24
        - 0.0.0.0/0

  # Ingress configuration
  ingress:
    # -- Whether to create an ingress resource
    enabled: false
    # -- Ingress annotations
    annotations: {}

  # -- Persistent storage configuration
  persistence:
    # -- Enable persistent storage
    enabled: false

    # -- Persistent storage size
    size: "10Gi"

    # -- Persistent storage class
    storageClass: "standard"

# Restore configuration
restore:
  # -- Whether to enable restore functionality
  enabled: false

  # -- The URL for a Home Assistant backup to be downloaded and restored
  url: ""
