nameOverride: null
fullnameOverride: null
homeassistant:
  adminSecret: null                # Should have two keys USERNAME and PASSWORD
  hostname: homeassistant.home
  image: ghcr.io/home-assistant/home-assistant:latest
  containerPort: 8123
  hostNetwork: false
  config:
    TZ: Europe/Berlin
  zigbeeDevice: null
  disableOnboarding: true
  storage: 1Gi
  reloader:
    image: kiwigrid/k8s-sidecar:latest
    webhook_id:                     # Generate a ramdon value to be used for reloading webhooks
    automations:
      enabled: true
      label: homeassistant.automations
    scripts:
      enabled: true
      label: homeassistant.scripts
    scenes:
      enabled: true
      label: homeassistant.scenes
    themes:
      enabled: true
      label: homeassistant.themes

  initConfig: |
    default_config:

    homeassistant:
      name: Home
      latitude: 31.7780191
      longitude: 35.2354079
      elevation: 747
      unit_system: metric
      currency: JOD
      country: PS
      time_zone: "Asia/Jerusalem"
      language: "en"


    frontend:
      themes: !include_dir_merge_named themes

    tts:
      - platform: google_translate

    automation: !include_dir_list automations
    script: !include_dir_list scripts
    scene: !include_dir_list scenes
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/24
        - 0.0.0.0/0
