apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- .Values.homeassistant.initConfig | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-automations
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- range $fileName, $content := .Values.homeassistant.automations }}
  {{ $fileName }}: |
{{ toYaml $content | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-themes
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- range $fileName, $content := .Values.homeassistant.themes }}
  {{ $fileName }}: |
{{ toYaml $content | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-scripts
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- range $fileName, $content := .Values.homeassistant.scripts }}
  {{ $fileName }}: |
{{ toYaml $content | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-scenes
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- range $fileName, $content := .Values.homeassistant.scenes }}
  {{ $fileName }}: |
{{ toYaml $content | indent 4 }}
{{- end }}
