apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
  configuration.yaml: |
    {{- .Values.homeassistant.initConfig | nindent 4 }}
---
{{- if and .Values.homeassistant.automations (gt (len .Values.homeassistant.automations ) 0) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homeassistant.fullname" . }}-automations
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
data:
{{- range $fileName, $content := .Values.homeassistant.automations }}
  {{ $fileName }}: |
{{ toYaml $content | indent 4 }}
{{- end }}
{{- end }}
