apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{ include "homeassistant.fullname" . }}
      hostNetwork: {{ .Values.homeassistant.hostNetwork }}
      initContainers:
      - name: wait-for-backup-restore
        image: ghcr.io/groundnuty/k8s-wait-for:v1.6
        args:
          - job
          - {{ include "homeassistant.fullname" . }}-restore-backup
      containers:
      - name: homeassistant
        image: {{ .Values.homeassistant.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: {{ include "homeassistant.fullname" . }}
          mountPath: /config/
        - name: config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        - name: disable-onboarding
          mountPath: /config/.storage/onboarding
          subPath: onboarding
        - name: reload-webhooks
          mountPath: /config/automations/reload-webhooks/
        - name: automations
          mountPath: /config/automations/
        - name: themes
          mountPath: /config/themes/
        - name: scenes
          mountPath: /config/scenes/
        - name: scripts
          mountPath: /config/scripts/
        {{- with .Values.homeassistant.config.zigbeeDevice }}
        - name: zigbee-device
          mountPath: {{ .Values.homeassistant.config.zigbeeDevice }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.homeassistant.containerPort }}
          name: http
        env:
        - name: TZ
          value: {{ .Values.homeassistant.config.TZ }}
      {{- if .Values.homeassistant.reloader.automations.enabled }}
      - name: config-reloader-automations
        image: {{ .Values.homeassistant.reloader.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: automations
          mountPath: /config/automations/
        env:
        - name: LABEL
          value: {{ .Values.homeassistant.reloader.automations.label }}
        - name: FOLDER
          value: /config/automations/
        - name: RESOURCE
          value: both
        - name: REQ_METHOD
          value: POST
        - name: REQ_URL
          value: http://127.0.0.1:8123/api/webhook/{{ .Values.homeassistant.reloader.webhook_id }}-automations
      {{- end }}
      {{- if .Values.homeassistant.reloader.themes.enabled }}
      - name: config-reloader-themes
        image: {{ .Values.homeassistant.reloader.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: themes
          mountPath: /config/themes/
        env:
        - name: LABEL
          value: {{ .Values.homeassistant.reloader.themes.label }}
        - name: FOLDER
          value: /config/themes/
        - name: RESOURCE
          value: both
        - name: REQ_METHOD
          value: POST
        - name: REQ_URL
          value: http://127.0.0.1:8123/api/webhook/{{ .Values.homeassistant.reloader.webhook_id }}-themes
      {{- end }}
      {{- if .Values.homeassistant.reloader.scripts.enabled }}
      - name: config-reloader-scripts
        image: {{ .Values.homeassistant.reloader.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: scripts
          mountPath: /config/scripts/
        env:
        - name: LABEL
          value: {{ .Values.homeassistant.reloader.scripts.label }}
        - name: FOLDER
          value: /config/scripts/
        - name: RESOURCE
          value: both
        - name: REQ_METHOD
          value: POST
        - name: REQ_URL
          value: http://127.0.0.1:8123/api/webhook/{{ .Values.homeassistant.reloader.webhook_id }}-scripts
      {{- end }}
      {{- if .Values.homeassistant.reloader.scenes.enabled }}
      - name: config-reloader-scenes
        image: {{ .Values.homeassistant.reloader.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: scenes
          mountPath: /config/scenes/
        env:
        - name: LABEL
          value: {{ .Values.homeassistant.reloader.scenes.label }}
        - name: FOLDER
          value: /config/scenes/
        - name: RESOURCE
          value: both
        - name: REQ_METHOD
          value: POST
        - name: REQ_URL
          value: http://127.0.0.1:8123/api/webhook/{{ .Values.homeassistant.reloader.webhook_id }}-scenes
      {{- end }}
      volumes:
      {{- with .Values.homeassistant.config.zigbeeDevice }}
      - name: zigbee-device
        hostPath:
          path: {{ . }}
          type: ""
      {{- end }}
      - name: config
        configMap:
          name: {{ include "homeassistant.fullname" . }}
      - name: automations
        emptyDir: {}
      - name: scenes
        emptyDir: {}
      - name: themes
        emptyDir: {}
      - name: scripts
        emptyDir: {}
      - name: reload-webhooks
        configMap:
          name: {{ include "homeassistant.fullname" . }}-reload-webhooks
      - name: disable-onboarding
        configMap:
          name: {{ include "homeassistant.fullname" . }}-disable-onboarding
      - name: {{ include "homeassistant.fullname" . }}
        persistentVolumeClaim:
          claimName: {{ include "homeassistant.fullname" . }}
