apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ .Values.homeassistant.hostname }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ include "homeassistant.fullname" . }}
            port:
              name: http
        pathType: ImplementationSpecific
