apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "homeassistant.fullname" . }}-wait-job
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "homeassistant.fullname" . }}-wait-job-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "homeassistant.fullname" . }}-wait-job
subjects:
- kind: ServiceAccount
  name: {{ include "homeassistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
