apiVersion: v1
kind: Service
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
  {{- with .Values.homeassistant.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.homeassistant.service.type }}
  ports:
  - port: {{ .Values.homeassistant.service.port }}
    targetPort: http
    name: http
  selector:
    {{- include "homeassistant.selectorLabels" . | nindent 4 }}
