apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8}}
    spec:
      hostNetwork: {{ .Values.homeassistant.hostNetwork }}
      initContainers:
      - name: init
        image: busybox
        command: ["sh"]
        args:
        - -c
        - "[ -f /app/data/configuration.yaml ] || cp /configuration.yaml /app/data/"
        volumeMounts:
        - name: {{ include "homeassistant.fullname" . }}
          mountPath: /app/data
        - name: config
          mountPath: /configuration.yaml
          subPath: configuration.yaml
      containers:
      - name: homeassistant
        image: {{ .Values.homeassistant.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: {{ include "homeassistant.fullname" . }}
          mountPath: /config
        {{- with .Values.homeassistant.config.zigbeeDevice }}
        - name: zigbee-device
          mountPath: {{ .Values.homeassistant.config.zigbeeDevice }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.homeassistant.containerPort }}
          name: http
        env:
        - name: TZ
          value: {{ .Values.homeassistant.config.TZ }}
      volumes:
      {{- with .Values.homeassistant.config.zigbeeDevice }}
      - name: zigbee-device
        hostPath:
          path: {{ . }}
          type: ""
      {{- end }}
      - name: config
        configMap:
          name: {{ include "homeassistant.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "homeassistant.fullname" . }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.homeassistant.storage }}
