apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8}}
    spec:
      hostNetwork: {{ .Values.homeassistant.hostNetwork }}
      containers:
      - name: homeassistant
        image: {{ .Values.homeassistant.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: {{ include "homeassistant.fullname" . }}
          mountPath: /config/
        - name: config
          mountPath: /config/configuration.yaml
          subPath: configuration.yaml
        - name: automations
          mountPath: /config/automations/
        - name: themes
          mountPath: /config/themes/
        - name: scenes
          mountPath: /config/scenes/
        - name: scripts
          mountPath: /config/scripts/
        {{- with .Values.homeassistant.config.zigbeeDevice }}
        - name: zigbee-device
          mountPath: {{ .Values.homeassistant.config.zigbeeDevice }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.homeassistant.containerPort }}
          name: http
        env:
        - name: TZ
          value: {{ .Values.homeassistant.config.TZ }}
      volumes:
      {{- with .Values.homeassistant.config.zigbeeDevice }}
      - name: zigbee-device
        hostPath:
          path: {{ . }}
          type: ""
      {{- end }}
      - name: config
        configMap:
          name: {{ include "homeassistant.fullname" . }}
      - name: automations
        configMap:
          name: {{ include "homeassistant.fullname" . }}-automations
      - name: scenes
        configMap:
          name: {{ include "homeassistant.fullname" . }}-scenes
      - name: themes
        configMap:
          name: {{ include "homeassistant.fullname" . }}-themes
      - name: scripts
        configMap:
          name: {{ include "homeassistant.fullname" . }}-scripts
  volumeClaimTemplates:
  - metadata:
      name: {{ include "homeassistant.fullname" . }}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.homeassistant.storage }}
