zigbee2mqtt:
  image: koenkk/zigbee2mqtt
  replicas: 1
  config:
    TZ: "Europe/Berlin"
    zigbee_device: /dev/ttyUSB0

  initConfig:
    # These will be applied ONLY on first run
    # Home Assistant integration (MQTT discovery)
    homeassistant: true

    # allow new devices to join
    # WARNING: Disable this after all devices have been paired! (default: false)
    # Note: this will be controllable in the UI
    permit_join: true
    frontend: true

    # MQTT settings
    mqtt:
      # MQTT base topic for zigbee2mqtt MQTT messages
      base_topic: zigbee2mqtt
      # MQTT server URL
      server: "mqtt://mosquitto"
      include_device_information: true
    serial:
      port: /dev/ttyUSB0

    advanced:
      network_key: GENERATE
      log_output:
        - console
      log_level: info
      last_seen: "ISO_8601"

      homeassistant_discovery_topic: "homeassistant"
      homeassistant_status_topic: "homeassistant/status"

      # Optional: Enables report feature (see information -> report for more details) (default: false)
      # report: true

      # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
      # elapsed: true

