apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-homeassistant-config
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  configuration.yaml: |
    {{- .Values.homeassistant.initConfig | nindent 4 -}}
