apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-homeassistant
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: {{ .Values.homeassistant.hostname }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: {{ .Release.Name }}-ha-web
            port:
              name: http
        pathType: ImplementationSpecific
