apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ha-web
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - port: 80
    targetPort: http
    name: http
  selector:
    app: {{ .Release.Name }}-homeassistant
