apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "homeassistant.fullname" . }}
  labels:
    {{- include "homeassistant.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "homeassistant.fullname" . }}
  selector:
    matchLabels:
      {{- include "homeassistant.selectorLabels" . | nindent 6}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "homeassistant.selectorLabels" . | nindent 8}}
    spec:
      hostNetwork: {{ .Values.homeassistant.hostNetwork }}
      initContainers:
        - name: init
          image: busybox
          command: ["sh"]
          args:
          - -c
          - "[ -f /app/data/configuration.yaml ] || cp /configuration.yaml /app/data/"
          volumeMounts:
            - name: data
              mountPath: /app/data
            - name: config
              mountPath: /configuration.yaml
              subPath: configuration.yaml
      containers:
      - name: homeassistant
        image: {{ .Values.homeassistant.image }}
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: data
            mountPath: /config
        {{- with .Values.homeassistant.zigbeeDevice }}
          - name: zigbee-device
            mountPath: {{ .Values.homeassistant.zigbeeDevice }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.homeassistant.containerPort }}
          name: http
        env:
        - name: TZ
          value: "{{ .Values.homeassistant.config.TZ }}"
      volumes:
      - name: zigbee-device
        hostPath:
          path: "{{ .Values.homeassistant.config.zigbee_device }}"
          type: ""
      - name: config
        configMap:
          name: "{{ .Release.Name }}-homeassistant-config"
  volumeClaimTemplates:
    - metadata:
        name: {{ include "homeassitant.fullname" . }}
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.homeassistant.storage }}
