homeassistant:
  hostname: homeassistant.home
  image: ghcr.io/home-assistant/home-assistant:stable
  config:
    TZ: "Europe/Berlin"
    zigbee_device: /dev/ttyUSB0

  initConfig:
    default_config: ""
    frontend:
      themes: "!include_dir_merge_named themes"

    tts:
      - platform: google_translate

    automation: "!include automations.yaml"
    script: "!include scripts.yaml"
    scene: "!include scenes.yaml"
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.42.0.0/24
